### ISSUE TITLE
Allow custom logging in docker2aci lib.

### ISSUE THREAD

**Issue by krnowak** [appc/docker2aci#136]
Something to consider before releasing 1.0 in a separate PR - replace the `pkg/log` with a `Logger` field in the `CommonConfig` struct, so users can pass their own logger. The `Logger` fields would be of some interface type like:

``` go
type Logger interface {
    Debug(i ...interface{})
    Info(i ...interface{})
}
```

so the implementer could implement the `Debug` function in the same way as currently `pkg/log` does without resorting to some global boolean variable set by the `InitDebug()` function. Possibly export two implementation like `DefaultLogger` with configurable debugging function and `DevNullLogger`.

**Comment by lucab** [comment]
logrus defines a generic [StdLogger](https://godoc.org/github.com/Sirupsen/logrus#StdLogger) interface and a more rich [FieldLogger](https://godoc.org/github.com/Sirupsen/logrus#FieldLogger) for this purpose.

**Comment by s-urbaniak** [comment]
My proposition is to use a minimalistic stdlib-compatible logger interface, not imposing log levels on the user of the library, since this concept is unknown in stdlib. I have a local branch working with the following (also logrus compatible) signature:

```
package log

type Logger interface {
	Print(...interface{})
	Printf(string, ...interface{})
	Println(...interface{})
}
```

We provide a `StdLogger` instanciating a stdlib logger using https://godoc.org/log#New used by the CLI `main.go`.

The user of the library is free to inject any Logger where we introduce two new members in [CommonConfig](https://github.com/appc/docker2aci/blob/master/lib/docker2aci.go#L45):
```
type CommonConfig struct {
	Squash      bool               // squash the layers in one file
	OutputDir   string             // where to put the resulting ACI
	TmpDir      string             // directory to use for temporary files
	Compression common.Compression // which compression to use for the resulting file(s)

	Info  log.Logger
	Debug log.Logger
}
```

To retain backwards compatibility we initialize the logger properly in case they are undefined:
```
func (c *CommonConfig) initLogger() {
	if c.Info == nil {
		c.Info = log.NewStdLogger(os.Stderr)
	}

	if c.Debug == nil {
		c.Debug = log.NewNopLogger()
	}
}
```

The above method is called inside `ConvertSavedFile`, and `ConvertRemoteRepo`. The signatures of the previously mentioned methods remain unchanged, only two fields are added, retaining backwards compatibility .... at least for this issue.
