### ISSUE TITLE
docker://debian wrong symlink container/var/lock -> /run/lock

### ISSUE THREAD

**Issue by aatdark** [appc/docker2aci#241]
i pulled the debian latest using:
`acbuild begin docker://library/debian:latest`
which uses docker2aci internally afaik.

after investigating a package installation issue (schroot) in the container i found the source of the problem
in the container filesystem: 

the lock folder is a symlink to` /run/lock` (not to `.acbuild/currentaci/rootfs/run/lock` as think it should be).
```
.acbuild/currentaci/rootfs/var # ls -la
lrwxrwxrwx  1 root root    9 16. Jan 19:02 lock -> /run/lock
```
because the running container can not access /run/lock of the host system each write access leads to an error. (overlay fs)

i'm using **rkt 1.23.0** - from this git page [0] is assume that the **docker2aci  is: 0.15.0**

[0] https://github.com/coreos/rkt/tree/v1.23.0/vendor/github.com/appc

**Comment by dgonyeo** [comment]
Note that symlink paths don't care whether or not you're in a chroot. When you look at a symlink that points to `/run/lock`, it will point to `/run/lock` from your shell and it will also point to `/run/lock` from _inside_ the container. So if some process is in an `acbuild run` command (and thus chrooted) when it tries to follow the symlink to `/run/lock` it will end up at `.acbuild/currentaci/rootfs/run/lock`. Where the symlink points to effectively changes when you're inside a chroot.

Does that help at all?

**Comment by aatdark** [comment]
ok this makes sense, but why is this failing?:
```
[root tmp]# acbuild begin docker://library/debian:latest
[root tmp]# acbuild run -- /bin/bash -c "touch /var/lock/a"
touch: cannot touch '/var/lock/a': No such file or directory
[root tmp]# acbuild run -- /bin/bash -c "ls -la /var/lock"
lrwxrwxrwx 1 root root 9 Jan 16 19:02 /var/lock -> /run/lock
[root@zero tmp]# acbuild run -- /bin/bash -c "ls -la /run/lock"
ls: cannot access /run/lock: No such file or directory
```
but:
```
[root@zero tmp]# ls -la .acbuild/currentaci/rootfs/run/lock/
total 0
drwxrwxrwt 2 root root 40 16. Jan 19:02 .
```

i guess this is a rkt bug then and not a docker2aci issue?

**Comment by dgonyeo** [comment]
This is actually an acbuild quirk. If you look at a log of me poking around [here](http://lpaste.net/4896310168238686208), you'll see in the mounts inside an `acbuild run` command a tmpfs mounted at `/run`. This means that while outside the container you'll see the `/run/lock` directory exist, it doesn't to processes inside the container, because an empty tmpfs is mounted over `/run`.

This is being done by `systemd-nspawn`, which is the default run engine in acbuild. If you add a `--engine=chroot` to the run commands, you can switch to the chroot engine, which shouldn't do anything aside from a basic chroot.

Also note that acbuild doesn't use rkt to run its containers. If you run a `mount | grep run` command inside a rkt container (logs [here](http://lpaste.net/464858097291100160)) you'll see that `/run` doesn't have anything mounted over it, so I would expect your example to work if you were using rkt to run the container.

**Comment by aatdark** [comment]
ok thanks for investigating this! it is obviously not an docker2aci problem.

**Comment by dgonyeo** [comment]
I'm hoping to eventually implement a runc engine for acbuild and make that the default. Haven't explored the implications that much yet, but I'm hoping some of the quirks like this will go away. A tmpfs is also mounted at `/tmp`, and I've gotten a steady rate of confused users asking why `acbuild run -- /bin/sh -c "echo test > /tmp/test"` doesn't work.
